import { AaAbilityApi } from "@/app/api/api/aa-ability-api"
import { AccountApi } from "@/app/api/api/account-api"
import { AdventureTemplateApi } from "@/app/api/api/adventure-template-api"
import { AlternateCurrencyApi } from "@/app/api/api/alternate-currency-api"
import { AuraApi } from "@/app/api/api/aura-api"
import { BlockedSpellApi } from "@/app/api/api/blocked-spell-api"
import { CharacterDatumApi } from "@/app/api/api/character-datum-api"
import { CharacterParcelApi } from "@/app/api/api/character-parcel-api"
import { ChatchannelApi } from "@/app/api/api/chatchannel-api"
import { ContentFlagApi } from "@/app/api/api/content-flag-api"
import { DataBucketApi } from "@/app/api/api/data-bucket-api"
import { DoorApi } from "@/app/api/api/door-api"
import { DynamicZoneTemplateApi } from "@/app/api/api/dynamic-zone-template-api"
import { FactionListApi } from "@/app/api/api/faction-list-api"
import { FishingApi } from "@/app/api/api/fishing-api"
import { ForageApi } from "@/app/api/api/forage-api"
import { GraveyardApi } from "@/app/api/api/graveyard-api"
import { GridApi } from "@/app/api/api/grid-api"
import { GroundSpawnApi } from "@/app/api/api/ground-spawn-api"
import { GuildApi } from "@/app/api/api/guild-api"
import { InventoryApi } from "@/app/api/api/inventory-api"
import { KeyringApi } from "@/app/api/api/keyring-api"
import { MailApi } from "@/app/api/api/mail-api"
import { ObjectApi } from "@/app/api/api/object-api"
import { QuestGlobalApi } from "@/app/api/api/quest-global-api"
import { RaidMemberApi } from "@/app/api/api/raid-member-api"
import { SharedTaskApi } from "@/app/api/api/shared-task-api"
import { Spawn2Api } from "@/app/api/api/spawn2-api"
import { SpawngroupApi } from "@/app/api/api/spawngroup-api"
import { TitleApi } from "@/app/api/api/title-api"
import { TradeskillRecipeApi } from "@/app/api/api/tradeskill-recipe-api"
import { TrapApi } from "@/app/api/api/trap-api"

export type PeqIdQuery = {
  field: string
  query: string
}

export type PeqTableConfig = {
  Api: any
  list: string
  create: string
  update: string
  delete: string
  count?: string
  bodyKey: string
  searchFields: string[]
  orderBy: string[]
  orderDirection?: string
  hideColumns?: string[]
  select?: string[]
  zoneField?: string
  zoneFieldIsId?: boolean
  idField?: string
  idQuery?: PeqIdQuery[]
  rowKeyFields?: string[]
  allowCreate?: boolean
  allowDelete?: boolean
  rowActions?: { label: string; to: string | ((row: any) => string) }[]
  newRow: Record<string, any>
}

const TABLES: Record<string, PeqTableConfig> = {
  spawns: {
    Api: Spawn2Api,
    list: "listSpawn2s",
    create: "createSpawn2",
    update: "updateSpawn2",
    delete: "deleteSpawn2",
    count: "getSpawn2sCount",
    bodyKey: "spawn2",
    searchFields: ["zone", "id"],
    orderBy: ["id"],
    hideColumns: ["spawnentries", "spawngroup"],
    zoneField: "zone",
    newRow: { zone: "qeynos", version: 0, x: 0, y: 0, z: 0, heading: 0, respawntime: 60, variance: 0, pathgrid: 0, spawngroup_id: 0 },
  },
  spawngroups: {
    Api: SpawngroupApi,
    list: "listSpawngroups",
    create: "createSpawngroup",
    update: "updateSpawngroup",
    delete: "deleteSpawngroup",
    count: "getSpawngroupsCount",
    bodyKey: "spawngroup",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    hideColumns: ["spawn_2", "spawnentries"],
    newRow: { name: "New Spawngroup", spawn_limit: 0, dist: 0, max_x: 0, min_x: 0, max_y: 0, min_y: 0, delay: 0 },
  },
  factions: {
    Api: FactionListApi,
    list: "listFactionLists",
    create: "createFactionList",
    update: "updateFactionList",
    delete: "deleteFactionList",
    count: "getFactionListsCount",
    bodyKey: "factionList",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    newRow: { name: "New Faction", base: 0 },
  },
  tradeskills: {
    Api: TradeskillRecipeApi,
    list: "listTradeskillRecipes",
    create: "createTradeskillRecipe",
    update: "updateTradeskillRecipe",
    delete: "deleteTradeskillRecipe",
    count: "getTradeskillRecipesCount",
    bodyKey: "tradeskillRecipe",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    newRow: { name: "New Recipe", tradeskill: 0, trivial: 0, enabled: 1 },
  },
  doors: {
    Api: DoorApi,
    list: "listDoors",
    create: "createDoor",
    update: "updateDoor",
    delete: "deleteDoor",
    count: "getDoorsCount",
    bodyKey: "door",
    searchFields: ["name", "zone", "id"],
    orderBy: ["id"],
    hideColumns: ["item"],
    zoneField: "zone",
    newRow: { zone: "qeynos", version: 0, name: "DOOR", doorid: 1, pos_x: 0, pos_y: 0, pos_z: 0, heading: 0 },
  },
  traps: {
    Api: TrapApi,
    list: "listTraps",
    create: "createTrap",
    update: "updateTrap",
    delete: "deleteTrap",
    count: "getTrapsCount",
    bodyKey: "trap",
    searchFields: ["zone", "id"],
    orderBy: ["id"],
    zoneField: "zone",
    newRow: { zone: "qeynos", version: 0, x: 0, y: 0, z: 0, radius: 10, effect: 0, chance: 100 },
  },
  "ground-spawns": {
    Api: GroundSpawnApi,
    list: "listGroundSpawns",
    create: "createGroundSpawn",
    update: "updateGroundSpawn",
    delete: "deleteGroundSpawn",
    count: "getGroundSpawnsCount",
    bodyKey: "groundSpawn",
    searchFields: ["comment", "id"],
    orderBy: ["id"],
    hideColumns: ["zone"],
    zoneField: "zoneid",
    zoneFieldIsId: true,
    newRow: { zoneid: 1, version: 0, item: 1001, max_x: 0, max_y: 0, max_z: 0, min_x: 0, min_y: 0, respawn_timer: 300 },
  },
  forage: {
    Api: ForageApi,
    list: "listForages",
    create: "createForage",
    update: "updateForage",
    delete: "deleteForage",
    count: "getForagesCount",
    bodyKey: "forage",
    searchFields: ["id"],
    orderBy: ["id"],
    hideColumns: ["item", "zone"],
    zoneField: "zoneid",
    zoneFieldIsId: true,
    newRow: { zoneid: 1, itemid: 1001, level: 0, chance: 10 },
  },
  fishing: {
    Api: FishingApi,
    list: "listFishings",
    create: "createFishing",
    update: "updateFishing",
    delete: "deleteFishing",
    count: "getFishingsCount",
    bodyKey: "fishing",
    searchFields: ["id"],
    orderBy: ["id"],
    hideColumns: ["item", "zone", "npc_type"],
    zoneField: "zoneid",
    zoneFieldIsId: true,
    newRow: { zoneid: 1, itemid: 1001, skill_level: 0, chance: 10 },
  },
  objects: {
    Api: ObjectApi,
    list: "listObjects",
    create: "createObject",
    update: "updateObject",
    delete: "deleteObject",
    count: "getObjectsCount",
    bodyKey: "object",
    searchFields: ["objectname", "display_name", "id"],
    orderBy: ["id"],
    hideColumns: ["item", "zone"],
    zoneField: "zoneid",
    zoneFieldIsId: true,
    newRow: { zoneid: 1, version: 0, objectname: "IT63_ACTORDEF", xpos: 0, ypos: 0, zpos: 0 },
  },
  graveyards: {
    Api: GraveyardApi,
    list: "listGraveyards",
    create: "createGraveyard",
    update: "updateGraveyard",
    delete: "deleteGraveyard",
    count: "getGraveyardsCount",
    bodyKey: "graveyard",
    searchFields: ["id"],
    orderBy: ["id"],
    zoneField: "zone_id",
    zoneFieldIsId: true,
    newRow: { zone_id: 1, x: 0, y: 0, z: 0, heading: 0 },
  },
  "blocked-spells": {
    Api: BlockedSpellApi,
    list: "listBlockedSpells",
    create: "createBlockedSpell",
    update: "updateBlockedSpell",
    delete: "deleteBlockedSpell",
    count: "getBlockedSpellsCount",
    bodyKey: "blockedSpell",
    searchFields: ["description", "id"],
    orderBy: ["id"],
    zoneField: "zoneid",
    zoneFieldIsId: true,
    newRow: { zoneid: 1, spellid: 0, type: 1, x: 0, y: 0, z: 0 },
  },
  aas: {
    Api: AaAbilityApi,
    list: "listAaAbilities",
    create: "createAaAbility",
    update: "updateAaAbility",
    delete: "deleteAaAbility",
    count: "getAaAbilitiesCount",
    bodyKey: "aaAbility",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    newRow: { name: "New AA", enabled: 1, type: 1, first_rank_id: 0 },
  },
  databuckets: {
    Api: DataBucketApi,
    list: "listDataBuckets",
    create: "createDataBucket",
    update: "updateDataBucket",
    delete: "deleteDataBucket",
    count: "getDataBucketsCount",
    bodyKey: "dataBucket",
    searchFields: ["key", "id"],
    orderBy: ["id"],
    newRow: { key: "new_key", value: "0", character_id: 0, npc_id: 0, bot_id: 0 },
  },
  "content-flags": {
    Api: ContentFlagApi,
    list: "listContentFlags",
    create: "createContentFlag",
    update: "updateContentFlag",
    delete: "deleteContentFlag",
    count: "getContentFlagsCount",
    bodyKey: "contentFlag",
    searchFields: ["flag_name", "id"],
    orderBy: ["id"],
    newRow: { flag_name: "new_flag", enabled: 0, notes: "" },
  },
  adventures: {
    Api: AdventureTemplateApi,
    list: "listAdventureTemplates",
    create: "createAdventureTemplate",
    update: "updateAdventureTemplate",
    delete: "deleteAdventureTemplate",
    count: "getAdventureTemplatesCount",
    bodyKey: "adventureTemplate",
    searchFields: ["zone", "text", "id"],
    orderBy: ["id"],
    zoneField: "zone",
    newRow: { zone: "gukbottom", theme: 1, min_level: 1, max_level: 65, type: 1, duration: 3600 },
  },
  altcur: {
    Api: AlternateCurrencyApi,
    list: "listAlternateCurrencies",
    create: "createAlternateCurrency",
    update: "updateAlternateCurrency",
    delete: "deleteAlternateCurrency",
    count: "getAlternateCurrenciesCount",
    bodyKey: "alternateCurrency",
    searchFields: ["id"],
    orderBy: ["id"],
    hideColumns: ["item"],
    newRow: { id: 0, item_id: 1001 },
  },
  titles: {
    Api: TitleApi,
    list: "listTitles",
    create: "createTitle",
    update: "updateTitle",
    delete: "deleteTitle",
    count: "getTitlesCount",
    bodyKey: "title",
    searchFields: ["prefix", "suffix", "id"],
    orderBy: ["id"],
    newRow: { prefix: "New Title", suffix: "", title_set: 0 },
  },
  auras: {
    Api: AuraApi,
    list: "listAuras",
    create: "createAura",
    update: "updateAura",
    delete: "deleteAura",
    count: "getAurasCount",
    bodyKey: "aura",
    searchFields: ["name", "type"],
    orderBy: ["type"],
    idField: "type",
    hideColumns: ["spells_new"],
    newRow: { type: 1, name: "New Aura", spell_id: 0, duration: 0, distance: 0 },
  },
  players: {
    Api: CharacterDatumApi,
    list: "listCharacterData",
    create: "createCharacterDatum",
    update: "updateCharacterDatum",
    delete: "deleteCharacterDatum",
    count: "getCharacterDataCount",
    bodyKey: "characterDatum",
    searchFields: ["name", "last_name", "id"],
    orderBy: ["id"],
    select: ["id", "account_id", "name", "last_name", "level", "class", "race", "zone_id", "gm", "xtargets"],
    rowActions: [{ label: "Inventory", to: (row) => "/editors/inventory?c=" + row.id }],
    newRow: { name: "NewPlayer", last_name: "", level: 1, race: 1, _class: 1, zone_id: 1, account_id: 1, xtargets: 5 },
  },
  "raid-roles": {
    Api: RaidMemberApi,
    list: "listRaidMembers",
    create: "createRaidMember",
    update: "updateRaidMember",
    delete: "deleteRaidMember",
    count: "getRaidMembersCount",
    bodyKey: "raidMember",
    searchFields: ["name", "raidid", "id"],
    orderBy: ["raidid", "groupid", "id"],
    select: ["id", "raidid", "charid", "name", "groupid", "israidleader", "isgroupleader", "is_assister", "is_marker", "note"],
    allowCreate: false,
    newRow: {},
  },
  pvp: {
    Api: CharacterDatumApi,
    list: "listCharacterData",
    create: "createCharacterDatum",
    update: "updateCharacterDatum",
    delete: "deleteCharacterDatum",
    count: "getCharacterDataCount",
    bodyKey: "characterDatum",
    searchFields: ["name", "id"],
    orderBy: ["pvp_current_points"],
    orderDirection: "desc",
    select: ["id", "name", "pvp_status", "pvp_kills", "pvp_deaths", "pvp_current_points", "pvp_career_points", "pvp_best_kill_streak", "pvp_current_kill_streak", "pvp_worst_death_streak", "pvp_type", "pvp2"],
    allowCreate: false,
    newRow: {},
  },
  accounts: {
    Api: AccountApi,
    list: "listAccounts",
    create: "createAccount",
    update: "updateAccount",
    delete: "deleteAccount",
    count: "getAccountsCount",
    bodyKey: "account",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    hideColumns: ["password", "crc_basedata", "crc_eqgame", "crc_skillcaps"],
    newRow: { name: "newaccount", status: 0, password: "" },
  },
  guilds: {
    Api: GuildApi,
    list: "listGuilds",
    create: "createGuild",
    update: "updateGuild",
    delete: "deleteGuild",
    count: "getGuildsCount",
    bodyKey: "guild",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    hideColumns: ["guild_banks", "guild_members", "guild_ranks"],
    newRow: { name: "New Guild", leader: 0, motd: "" },
  },
  mail: {
    Api: MailApi,
    list: "listMail",
    create: "createMail",
    update: "updateMail",
    delete: "deleteMail",
    count: "getMailCount",
    bodyKey: "mail",
    searchFields: ["subject", "from", "to", "msgid"],
    orderBy: ["msgid"],
    idField: "msgid",
    newRow: { charid: 0, from: "GM", to: "", subject: "New mail", body: "", status: 1 },
  },
  qglobals: {
    Api: QuestGlobalApi,
    list: "listQuestGlobals",
    create: "createQuestGlobal",
    update: "updateQuestGlobal",
    delete: "deleteQuestGlobal",
    count: "getQuestGlobalsCount",
    bodyKey: "questGlobal",
    searchFields: ["name", "value", "charid"],
    orderBy: ["charid"],
    idField: "charid",
    idQuery: [
      { field: "npcid", query: "npcid" },
      { field: "zoneid", query: "zoneid" },
      { field: "name", query: "name" },
    ],
    rowKeyFields: ["charid", "npcid", "zoneid", "name"],
    newRow: { charid: 0, npcid: 0, zoneid: 0, name: "new_global", value: "0" },
  },
  inventory: {
    Api: InventoryApi,
    list: "listInventories",
    create: "createInventory",
    update: "updateInventory",
    delete: "deleteInventory",
    count: "getInventoriesCount",
    bodyKey: "inventory",
    searchFields: ["character_id", "item_id"],
    orderBy: ["character_id"],
    idField: "character_id",
    idQuery: [{ field: "slot_id", query: "slot_id" }],
    rowKeyFields: ["character_id", "slot_id"],
    hideColumns: ["item"],
    newRow: { character_id: 0, slot_id: 0, item_id: 1001, charges: 1 },
  },
  "inventory-raw": {
    Api: InventoryApi,
    list: "listInventories",
    create: "createInventory",
    update: "updateInventory",
    delete: "deleteInventory",
    count: "getInventoriesCount",
    bodyKey: "inventory",
    searchFields: ["character_id", "item_id"],
    orderBy: ["character_id"],
    idField: "character_id",
    idQuery: [{ field: "slot_id", query: "slot_id" }],
    rowKeyFields: ["character_id", "slot_id"],
    hideColumns: ["item"],
    newRow: { character_id: 0, slot_id: 0, item_id: 1001, charges: 1 },
  },
  keys: {
    Api: KeyringApi,
    list: "listKeyrings",
    create: "createKeyring",
    update: "updateKeyring",
    delete: "deleteKeyring",
    count: "getKeyringsCount",
    bodyKey: "keyring",
    searchFields: ["char_id", "item_id", "id"],
    orderBy: ["id"],
    newRow: { char_id: 0, item_id: 1001 },
  },
  expeditions: {
    Api: DynamicZoneTemplateApi,
    list: "listDynamicZoneTemplates",
    create: "createDynamicZoneTemplate",
    update: "updateDynamicZoneTemplate",
    delete: "deleteDynamicZoneTemplate",
    count: "getDynamicZoneTemplatesCount",
    bodyKey: "dynamicZoneTemplate",
    searchFields: ["name", "id"],
    orderBy: ["id"],
    newRow: { name: "New Expedition", zone_id: 1, duration_seconds: 3600, min_players: 1, max_players: 6 },
  },
  sharedtasks: {
    Api: SharedTaskApi,
    list: "listSharedTasks",
    create: "createSharedTask",
    update: "updateSharedTask",
    delete: "deleteSharedTask",
    count: "getSharedTasksCount",
    bodyKey: "sharedTask",
    searchFields: ["id", "task_id"],
    orderBy: ["id"],
    newRow: { task_id: 0, is_locked: 0 },
  },
  chat: {
    Api: ChatchannelApi,
    list: "listChatchannels",
    create: "createChatchannel",
    update: "updateChatchannel",
    delete: "deleteChatchannel",
    count: "getChatchannelsCount",
    bodyKey: "chatchannel",
    searchFields: ["name", "owner", "id"],
    orderBy: ["id"],
    hideColumns: ["password"],
    newRow: { name: "NewChannel", owner: "", minstatus: 0 },
  },
  parcels: {
    Api: CharacterParcelApi,
    list: "listCharacterParcels",
    create: "createCharacterParcel",
    update: "updateCharacterParcel",
    delete: "deleteCharacterParcel",
    count: "getCharacterParcelsCount",
    bodyKey: "characterParcel",
    searchFields: ["from_name", "note", "id"],
    orderBy: ["id"],
    newRow: { char_id: 0, item_id: 1001, quantity: 1, from_name: "GM", note: "" },
  },
  grids: {
    Api: GridApi,
    list: "listGrids",
    create: "createGrid",
    update: "updateGrid",
    delete: "deleteGrid",
    count: "getGridsCount",
    bodyKey: "grid",
    searchFields: ["id"],
    orderBy: ["id"],
    hideColumns: ["grid_entries", "zone"],
    zoneField: "zoneid",
    zoneFieldIsId: true,
    newRow: { id: 1, zoneid: 1, type: 0, type_2: 0 },
  },
}

export function getPeqTableConfig(id: string): PeqTableConfig | undefined {
  return TABLES[id]
}
